-- Seed integration catalog with all 13 providers
INSERT INTO integration_catalog (provider_key, name, description, icon_key, category, auth_type, verticals, scopes, setup_instructions, tier_required, sort_order) VALUES
(
  'shopify',
  'Shopify',
  'Access orders, carts, customers, and products. Agents can look up order status and abandoned carts during calls.',
  'shopping-bag',
  'ecommerce',
  'api_key',
  ARRAY['ecommerce', 'retail'],
  ARRAY['read_orders', 'read_customers', 'read_checkouts', 'read_products'],
  '[{"step": 1, "text": "Open your Shopify Admin > Settings > Apps > Develop apps"}, {"step": 2, "text": "Create a new app and enable Admin API access"}, {"step": 3, "text": "Grant scopes: read_orders, read_customers, read_checkouts, read_products"}, {"step": 4, "text": "Install the app and copy the Admin API access token"}]'::jsonb,
  'starter',
  10
),
(
  'whatsapp',
  'WhatsApp Business',
  'Send and receive WhatsApp messages via Twilio. Enable two-way conversations with customers on their preferred channel.',
  'message-circle',
  'messaging',
  'api_key',
  ARRAY['ecommerce', 'retail', 'clinic', 'services'],
  ARRAY['messaging:send', 'messaging:receive'],
  '[{"step": 1, "text": "Sign up for Twilio and activate WhatsApp sandbox or production sender"}, {"step": 2, "text": "Copy your Twilio Account SID and Auth Token"}, {"step": 3, "text": "Enter your WhatsApp-enabled Twilio phone number"}, {"step": 4, "text": "Configure the webhook URL in your Twilio console"}]'::jsonb,
  'starter',
  20
),
(
  'google_cal',
  'Google Calendar',
  'Read availability and create bookings. Agents check real-time calendar slots and schedule appointments during calls.',
  'calendar',
  'calendar',
  'oauth2',
  ARRAY['clinic', 'services', 'ecommerce'],
  ARRAY['https://www.googleapis.com/auth/calendar.readonly', 'https://www.googleapis.com/auth/calendar.events'],
  '[{"step": 1, "text": "Click Connect to sign in with your Google account"}, {"step": 2, "text": "Grant Aurora access to read your calendar and create events"}, {"step": 3, "text": "Select which calendars agents can access"}]'::jsonb,
  'starter',
  30
),
(
  'google_sheets',
  'Google Sheets',
  'Export call results, campaign outcomes, and analytics to Google Sheets. Automated daily/weekly exports available.',
  'table',
  'spreadsheet',
  'oauth2',
  ARRAY['ecommerce', 'retail', 'clinic', 'services'],
  ARRAY['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file'],
  '[{"step": 1, "text": "Click Connect to sign in with your Google account"}, {"step": 2, "text": "Grant Aurora access to create and edit spreadsheets"}, {"step": 3, "text": "Choose which data to export (calls, campaigns, contacts)"}]'::jsonb,
  'starter',
  35
),
(
  'hubspot',
  'HubSpot CRM',
  'Two-way contact sync with deal and activity tracking. Agents access contact history and log call outcomes automatically.',
  'circle-dot',
  'crm',
  'oauth2',
  ARRAY['ecommerce', 'services', 'retail'],
  ARRAY['crm.objects.contacts.read', 'crm.objects.contacts.write', 'crm.objects.deals.read', 'crm.objects.deals.write'],
  '[{"step": 1, "text": "Click Connect to authorize with your HubSpot account"}, {"step": 2, "text": "Grant access to contacts, deals, and activities"}, {"step": 3, "text": "Map Aurora fields to HubSpot properties"}]'::jsonb,
  'growth',
  40
),
(
  'pipedrive',
  'Pipedrive',
  'Sync contacts and deals with Pipedrive. Agents update deal stages and add call notes in real time.',
  'git-branch',
  'crm',
  'api_key',
  ARRAY['services', 'ecommerce'],
  ARRAY['deals:read', 'deals:write', 'contacts:read', 'contacts:write', 'activities:write'],
  '[{"step": 1, "text": "Open Pipedrive Settings > Personal Preferences > API"}, {"step": 2, "text": "Copy your personal API token"}, {"step": 3, "text": "Paste the token below to connect"}]'::jsonb,
  'growth',
  50
),
(
  'freshsales',
  'Freshsales',
  'Connect Freshworks Freshsales for contact management and deal pipeline visibility during agent calls.',
  'sparkles',
  'crm',
  'api_key',
  ARRAY['services', 'ecommerce'],
  ARRAY['contacts:read', 'contacts:write', 'deals:read'],
  '[{"step": 1, "text": "Open Freshsales > Settings > API Settings"}, {"step": 2, "text": "Generate or copy your API key"}, {"step": 3, "text": "Enter your Freshsales domain and API key below"}]'::jsonb,
  'growth',
  60
),
(
  'zoho_crm',
  'Zoho CRM',
  'OAuth2 integration with Zoho CRM. Sync contacts, deals, and call activities with two-way data flow.',
  'database',
  'crm',
  'oauth2',
  ARRAY['services', 'ecommerce', 'clinic'],
  ARRAY['ZohoCRM.modules.contacts.READ', 'ZohoCRM.modules.contacts.WRITE', 'ZohoCRM.modules.deals.READ'],
  '[{"step": 1, "text": "Click Connect to sign in with your Zoho account"}, {"step": 2, "text": "Authorize Aurora to access your CRM contacts and deals"}, {"step": 3, "text": "Configure sync preferences"}]'::jsonb,
  'growth',
  70
),
(
  'salesforce',
  'Salesforce',
  'Enterprise-grade Salesforce integration. Full contact, opportunity, and activity sync with custom field mapping.',
  'cloud',
  'crm',
  'oauth2',
  ARRAY['services', 'ecommerce'],
  ARRAY['api', 'refresh_token', 'openid'],
  '[{"step": 1, "text": "Click Connect to authorize via Salesforce OAuth"}, {"step": 2, "text": "Grant Aurora API access to your Salesforce org"}, {"step": 3, "text": "Select objects to sync (Contacts, Leads, Opportunities)"}]'::jsonb,
  'pro',
  80
),
(
  'cliniko',
  'Cliniko',
  'Access patient records, appointments, and practitioner schedules. Purpose-built for allied health clinics.',
  'stethoscope',
  'ehr',
  'api_key',
  ARRAY['clinic'],
  ARRAY['patients:read', 'appointments:read', 'appointments:write', 'practitioners:read'],
  '[{"step": 1, "text": "Open Cliniko > Settings > Integrations > API Keys"}, {"step": 2, "text": "Generate a new API key with read access to patients and appointments"}, {"step": 3, "text": "Paste the API key below"}]'::jsonb,
  'starter',
  90
),
(
  'jane_app',
  'Jane App',
  'Connect Jane practice management for appointment booking, patient lookup, and schedule management.',
  'heart-pulse',
  'ehr',
  'api_key',
  ARRAY['clinic'],
  ARRAY['patients:read', 'appointments:read', 'appointments:write', 'staff:read'],
  '[{"step": 1, "text": "Open Jane > Settings > Integrations"}, {"step": 2, "text": "Generate an API key for external integrations"}, {"step": 3, "text": "Copy and paste the key below"}]'::jsonb,
  'starter',
  91
),
(
  'drchrono',
  'DrChrono',
  'EHR integration for medical practices. Access patient demographics, appointments, and clinical notes.',
  'activity',
  'ehr',
  'oauth2',
  ARRAY['clinic'],
  ARRAY['patients:read', 'calendar:read', 'calendar:write', 'clinical:read'],
  '[{"step": 1, "text": "Click Connect to authorize via DrChrono OAuth"}, {"step": 2, "text": "Grant access to patients, appointments, and clinical data"}, {"step": 3, "text": "Select which calendars to enable"}]'::jsonb,
  'growth',
  92
),
(
  'calcom',
  'Cal.com',
  'Open-source scheduling integration. Let agents book directly to team calendars with conflict detection.',
  'calendar-check',
  'calendar',
  'api_key',
  ARRAY['services', 'clinic'],
  ARRAY['bookings:read', 'bookings:write', 'availability:read'],
  '[{"step": 1, "text": "Open Cal.com > Settings > Developer > API Keys"}, {"step": 2, "text": "Create a new API key"}, {"step": 3, "text": "Paste the key below to connect"}]'::jsonb,
  'starter',
  31
)
ON CONFLICT (provider_key) DO NOTHING;
